package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-06-16T21:36:09.886+05:30
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "PojoCXFServiceService", 
                  wsdlLocation = "service.wsdl",
                  targetNamespace = "http://ws/") 
public class PojoCXFServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws/", "PojoCXFServiceService");
    public final static QName PojoCXFServicePort = new QName("http://ws/", "PojoCXFServicePort");
    static {
        URL url = PojoCXFServiceService.class.getResource("service.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(PojoCXFServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "service.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public PojoCXFServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PojoCXFServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PojoCXFServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PojoCXFService
     */
    @WebEndpoint(name = "PojoCXFServicePort")
    public PojoCXFService getPojoCXFServicePort() {
        return super.getPort(PojoCXFServicePort, PojoCXFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PojoCXFService
     */
    @WebEndpoint(name = "PojoCXFServicePort")
    public PojoCXFService getPojoCXFServicePort(WebServiceFeature... features) {
        return super.getPort(PojoCXFServicePort, PojoCXFService.class, features);
    }

}
