package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-08-26T20:09:39.261+05:30
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "GreetingService", 
                  wsdlLocation = "http://localhost:8080/GreetingService/Greeting?wsdl",
                  targetNamespace = "http://ws/") 
public class GreetingService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws/", "GreetingService");
    public final static QName GreetingPort = new QName("http://ws/", "GreetingPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/GreetingService/Greeting?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GreetingService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/GreetingService/Greeting?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GreetingService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GreetingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GreetingService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Greeting
     */
    @WebEndpoint(name = "GreetingPort")
    public Greeting getGreetingPort() {
        return super.getPort(GreetingPort, Greeting.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Greeting
     */
    @WebEndpoint(name = "GreetingPort")
    public Greeting getGreetingPort(WebServiceFeature... features) {
        return super.getPort(GreetingPort, Greeting.class, features);
    }

}
