package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-08-26T20:09:39.220+05:30
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://ws/", name = "Greeting")
@XmlSeeAlso({ObjectFactory.class})
public interface Greeting {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRequestHeaders", targetNamespace = "http://ws/", className = "client.GetRequestHeaders")
    @WebMethod
    @ResponseWrapper(localName = "getRequestHeadersResponse", targetNamespace = "http://ws/", className = "client.GetRequestHeadersResponse")
    public java.lang.String getRequestHeaders();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://ws/", className = "client.Hello")
    @WebMethod
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://ws/", className = "client.HelloResponse")
    public java.lang.String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
